version: '3.7'
services:
    SQL2019:
        image: sqldbawithabeard/dbachecksdemo
        ports:  
          - "15592:1433"
        networks: 
          - BeardsMagicNetwork
        volumes: 
          - C:\Users\mrrob\Documents\dbatools:/var/opt/mssql/backups
    SQL2019-1:
        image: sqldbawithabeard/dbachecksdemo
        ports:  
          - "15593:1433"
        networks: 
          - BeardsMagicNetwork
        volumes: 
          - C:\Users\mrrob\Documents\dbatools:/var/opt/mssql/backups
networks: 
  BeardsMagicNetwork:
